apiVersion: demo.kratix.io/v1alpha1
kind: NBAService
metadata:
  name: scoreboard-api
  namespace: kratix-demo
spec:
  name: scoreboard-api
  port: 8080
  team: team-courtside
  environment: staging
  image: kratix-demo/scoreboard-api:latest
  replicas: 2
  namespace: kratix-demo
